packages:
  - frontend
  - backend
  - packages/*

catalog:
  nestjs-zod: ^5.1.1
  typescript: ^5.9.3
  vite: ^8.0.0-beta.0
  zod: ^4.1.13

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@swc/core'
  - '@vercel/speed-insights'
  - esbuild
  - unrs-resolver

onlyBuiltDependencies:
  - argon2

overrides:
  vite: 'catalog:'
